{
 "title": "CAMERA DETAIL",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "GROUP",
    "query": {}
   },
   {
    "name": "CAMERA",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "CAMERA AVAILABILITY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "CAMERA" },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*):(.*)/",
        "$1"
       ],
       "text": "replaceAlias(/(.*):(.*)/, $1)",
       "$$hashKey": "object:57"
      }
     ],
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "CAM Status" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "SNMP Agent Availability" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*): (.*)/",
        "$2"
       ],
       "text": "replaceAlias(/(.*): (.*)/, $2)",
       "$$hashKey": "object:109"
      }
     ],
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "ICMP response time" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*): (.*)/",
        "$2"
       ],
       "text": "replaceAlias(/(.*): (.*)/, $2)",
       "$$hashKey": "object:136"
      }
     ],
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "ICMP loss" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "30m",
        "last"
       ],
       "text": "groupBy(30m, last)",
       "$$hashKey": "object:163"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*): (.*)/",
        "$2"
       ],
       "text": "replaceAlias(/(.*): (.*)/, $2)",
       "$$hashKey": "object:164"
      }
     ],
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "ICMP Availability 5m %" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "CAMERA RECORDINGS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Snapshot days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "CAM Recording Num Of Days" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Availability of recordings",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 13, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "100" ],
       "text": "scale(100)",
       "$$hashKey": "object:219"
      }
     ],
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "CAM Recording" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "CAM Recording" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "CAM Recording Image" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Recordings",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "100" ],
       "text": "scale(100)",
       "$$hashKey": "object:254"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*): (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/(.*): (.*)/, $1)",
       "$$hashKey": "object:255"
      }
     ],
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "CAM Recording" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "100" ],
       "text": "scale(100)",
       "$$hashKey": "object:277"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*): (.*)/",
        "$2"
       ],
       "text": "replaceAlias(/(.*): (.*)/, $2)",
       "$$hashKey": "object:278"
      }
     ],
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "CAMERA INFORMATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "CAMERA" },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "Serial Number" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Camera Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "Camera Model" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Firmware Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "Firmware Version" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$GROUP" },
     "host": { "filter": "$CAMERA" },
     "item": { "filter": "CPU Usage" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}